### ISSUE TITLE
Showing MediaQuery.maybeOf(context)?.textScaler ?? const TextScaler.linear(1) error on latest flutter version

### ISSUE THREAD

**Issue by debjeetproso** [fujidaiti/primer_progress_bar#20]
![error](https://github.com/fujidaiti/primer_progress_bar/assets/110148787/e3bdf191-d92c-46bd-8d10-f376af88978a)

showing this error on the latest flutter version

**Comment by fujidaiti** [comment]
@debjeetproso 

Thanks for your reporting. Can you tell me the output of `flutter doctor`?

**Comment by fujidaiti** [comment]
Sorry, I accidentally broke backwards compatibility in `v0.3.1`. I will work on it. 
I'll leave you with some workarounds that we can use for now:

- Update your Flutter version to 3.16.0 or higher, or
- use `primar_progress_bar: 0.3.0` in your pubspec.yaml (not `^0.3.0`).

**Comment by fujidaiti** [comment]
I've retracted `v0.3.1` on pub.dev.
 Please downgrade the package to `v0.3.0` or lower if you have been using `v0.3.1`.
