### ISSUE TITLE
maxLines parameter not working in SegmentedBarLegendStyle

### ISSUE THREAD

**Issue by berkeenesakt** [fujidaiti/primer_progress_bar#5]
The maxLines parameter in SegmentedBarLegendStyle does not seem to be working as expected. When I set maxLines to a value of 2, the legend items are still displays more than 2 segments. I have tried different values for maxLines, but it still have problem.

Steps to reproduce:

Create a PrimerProgressBar widget with a SegmentedBarLegendStyle that has a maxLines value of 2.
Add some Segment objects to the PrimerProgressBar widget.
Verify that the legend items are displayed more than maxLines.
Expected behavior: The legend items should be displayed as maxLines value, other segments should displays as Other.

Actual behavior: The legend items are displays regardless of the value of maxLines.

You can see the problem here, I set the maxLines value as 2 but 5 items shown.
<img width="205" alt="Screenshot 2023-07-03 at 10 37 28" src="https://github.com/fujidaiti/primer_progress_bar/assets/81863556/1d0582aa-35fc-480f-bfc6-9c82a4c66701">

**Comment by fujidaiti** [comment]
> You can see the problem here, I set the maxLines value as 2 but 5 items shown.

This is intended behavior. The maxLines parameter is the same as maxLines in Text widget. For example, maxLines=2 prevents the legend from growing beyond two lines (or rows).

If you want to control the number of segments to be displayed, you may just rebuild the progress bar with the desired number of segments.

P.S.  
Thanks for sending me the PR too.
I'm a little too busy right now, but I'll look at it later.
